### PR TITLE
Update of the website

### PR DESCRIPTION
**Pull request by gilardh**
Hi, 

Here are some suggestions for corrections:

- Fixed a path error
- Deleting spaces and unnecessary carriage return for standardization
- Remove unnecessary code
- Updated French translations
- Update 'Copyright 2011-2018' for ''Copyright 2011-2019'
- Update copyright text
- Update Italian language
- Update header languages files
- Update of the version of 'gulp-sass'
- Add the translation of the text 'Other versions'

I use the v0.53 of Hugo for my test.

Best regards.

### CODE REVIEW

**Comment by gilardh** [comment]
Hello,

I see issues on the website litecoin.org but i can not declare them on the project's github page at this address: https://github.com/litecoin-project/litecoin.org
Why?

Best regards

Gilardh

**Comment by thrasher-** [comment]
Do you mean this? https://github.com/litecoin-project/litecoin.org/issues. I've just enabled the issues section.

**Comment by thrasher-** [comment]
tACK

**Comment by gilardh** [comment]
> Do you mean this? https://github.com/litecoin-project/litecoin.org/issues. I've just enabled the issues section.

Thank you, that's exactly it.

**Pull request merged**
