### PR TITLE
Adding Bahasa Indonesia Translation

### PR DESCRIPTION
**Pull request by josikie**
Hello Litecoin Community and Team! I'm Josi Kie, currently I'm learning about code through open source project. I saw Litecoin site doesn't have Bahasa Indonesia translation. As an Indonesian and a member of Litecoin Community, I want to contribute Bahasa Indonesia translation for Litecoin site.

Thank you for the opportunity,
Josi Kie^^

### CODE REVIEW

**Comment by kcw-grunt** [comment]
Apa kabar @josikie !
Kita juga mau tolong di [Litewallet](litewallet.io).   Kita dari Litecoin Foundation juga.

**Comment by josikie** [comment]
Halo @kcw-grunt !
Kabar saya baik, terimakasih sudah bertanya. Bagaimana kabar Anda juga?
Dengan senang hati saya akan menerjemahkan [Litewallet](https://github.com/litecoin-project/litecoin.org/pull/litewallet.io). Terimakasih atas kesempatan dan kepercayaannya terhadap saya.

**Comment by josikie** [comment]
@kcw-grunt 
Dimana letak repository Litewallet?

**Comment by josikie** [comment]
@kcw-gruntsoftware 
Bagus! Saya akan mencoba untuk Android terlebih dahulu.

**Review by losh11 — CHANGES_REQUESTED** [review]
Please delete the following build files:
- `.hugo_build.lock`
- contents of `.vs`

Please unstage the following files from changes:
- `package-lock.json`
- style.css

When adding i18n please make sure to only make changes to your language's toml file. Also after the above changes are done, please squash your commit into a single commit.

**Comment by losh11** [comment]
There now seems to be a new file called `close` that needs to be removed.

**Comment by josikie** [comment]
Is there any change I need to do? Btw thank you

**Review by kcw-grunt — COMMENTED** [review]
@josikie When you squash, I'll look again.

**Comment by josikie** [comment]
@kcw-grunt 
I squash it

**Comment by kcw-grunt** [comment]
Congrats @josikie

**Comment by josikie** [comment]
Thank you! @kcw-grunt @losh11

**Pull request merged**
